Test cases for parameter decoding error.
salesforce/nimbus pull request #276
Opened 2020-08-31 02:10 UTC by sfdctaka

Adding test cases for decoding error. When decoding fails, e.g. a string is passed when a number is expected, the promise in Javascript will be rejected and therefore can be handled in `catch(error => {...})`.

This PR does not unify `error` object passed to the handler in `catch` between web view and JSCore. Web view uses `DecodeError` which is our custom `Error` struct where as JSCore uses `DecodingError` that is out-of-the-box from Apple. Unification of error class is out of the scope for this work.

An edge case was discovered while working on this PR. Suppose there is a native function that is expecting a `String` parameter. Then from Javascript a simple simple Javascript object is passed instead, like `{aaa:`bbb`}`. Decoding of such parameter fails in JSCore, however, in web view, the script handler passes this Javascript object as JSON string. Combined with `try? JSONDecoder().decode(type, from: data)` where `data` is data representation of that JSON string the code was failing to detect wrong type being passed. You can see how I handle that below in `WebViewConnection.swift`. Similarly, `null` being passed was failing to be detected so I fixed that too.

2020-08-31 02:12 UTC, sfdctaka commented on platforms/apple/Sources/Nimbus/WebViewConnection.swift
> +                            context.debugDescription == "Expected to decode String but found a dictionary instead." {
Detecting the type mismatch where JSON string was passed instead of a string as I found was by looking at the `incomingType` and `context.debugDescription`. I didn't want to use a string phrase for this detection but there was nothing else that I could use.

2020-08-31 15:19 UTC, threeve commented on platforms/apple/Sources/Nimbus/WebViewConnection.swift
> +                    if #available(iOS 13, macOS 10.15, *) {
I know it's an extremely edgy edge case, however this code path now makes it impossible to pass the string literal `"null"` as the value to a string parameter, because `JSONDecoder` will treat it as a missing `String` value, however it would have succeeded had it fallen through to the `as? T` branch below.

2020-09-01 06:35 UTC, sfdctaka commented
@threeve I observed that removing `debugDescription` from the condition actually suffices to determine whether a JSON notation object in string is a legit string or not.

I also attempted various approaches to solve the problem of identifying whether `"null"` is null or a string but this one turns out to be very difficult. I'm not sure if this is doable. Because both nulls reach our `decode` method as quoted string there is no inherent marker that could be used to make the distinction whether it is a null or a string.

As you saw it the code in my PR will fail on `"null"`. I tried the code in `main` branch and the `decode` method there will fail on `null` instead.

So my question now is, should we support `null` at all? And just keep supporting `"null"` as we have always been doing?

2020-09-03 16:43 UTC, threeve requested changes

2020-09-03 16:43 UTC, threeve commented on platforms/apple/Sources/Nimbus/WebViewConnection.swift
> +                    case let .typeMismatch(incomingType, _) = decodingError,
Unfortunately this is not going to work still. This will make it impossible to pass a string as a string if the value of the string contains valid JSON.

E.g., if you try to pass the string value `"[]"` it will fail here and not fall through to the cast below.

2020-09-04 00:38 UTC, sfdctaka commented on platforms/apple/Sources/Nimbus/WebViewConnection.swift
> +                    case let .typeMismatch(incomingType, _) = decodingError,
I will file a work item so we can work on RFC to resolve either by stringifying all parameters first or adding by new metadata approach.

2020-09-04 00:42 UTC, sfdctaka commented
Removed the test `testVerifyStringDecoderRejectsObject` and also the `do{try{...}}catch{...}` code block that attempted to handle the scenario where stringified JSON object failed to decode to generic `Dictionary`.

2020-09-08 14:21 UTC, paultiarks requested changes

2020-09-08 14:21 UTC, paultiarks commented on packages/test-www/test/shared-tests.js
> +function verifyStringDecoderRejectsObject() {
It looks like this test isn't being called?

2020-09-08 17:08 UTC, threeve commented on packages/test-www/test/shared-tests.js
> +function verifyStringDecoderRejectsObject() {
This is the test case that cannot currently pass on iOS. I think we should at least include a comment here to that effect.

2020-09-08 18:01 UTC, paultiarks approved these changes

2020-09-09 07:22 UTC, sfdctaka commented on platforms/apple/Sources/Nimbus/WebViewConnection.swift
> +                            context.debugDescription == "Expected to decode String but found a dictionary instead." {
Per conversation, punting.

2020-09-09 07:23 UTC, sfdctaka commented on packages/test-www/test/shared-tests.js
> +function verifyStringDecoderRejectsObject() {
I added a comment. Tell me if you rather just remove the function.

2020-09-10 14:57 UTC, threeve approved these changes

2020-09-10 16:58 UTC, merged